### ISSUE TITLE
Provided checkpoint model is inconsistent with the latest code

### ISSUE THREAD

**Issue by lym29** [PKU-EPIC/UniDexGrasp#12]
Hi, when I try to run the eval code using the checkpoints you provided, there are parameters that have mismach size. I was trying to figure out it by myself but none of my attempts worked... Could you please provide a little help ? Thanks a lot!  

Here is the output for ipdf model:  

> RuntimeError: Error(s) in loading state_dict for IPDFModel:  
>        size mismatch for net.implicit_model.feat_mlp.weight: copying a param with shape torch.Size([256, 64]) from checkpoint,  
>the shape in current model is torch.Size([256, 128]).

**Comment by lym29** [comment]
```python
self.mlp_layer_sizes = cfg["model"]["mlp_layer_sizes"]  # [256, 256, 256] 
if cfg["model"]["network"]["type"] == "epn_net": 
    self.input_feat_dim = cfg["model"]["network"]["equi_feat_mlps"][-1]  # 64 
elif cfg["model"]["network"]["type"] in ["pn_rotation_net", "kpconv_rot_net"]: 
    self.input_feat_dim = 128 
```
In [ipdf_network.py](https://github.com/PKU-EPIC/UniDexGrasp/blob/main/dexgrasp_generation/network/models/graspipdf/ipdf_network.py#L361C9-L365C38) it shows that if the type of ImplicitModel is 'pn_rotation_net', then the input feat dim is 128. But after loading the checkpoint in RotationNet/Dv3Rot, the output of input_feat_dim is 64. So I checked the config file [ipdf.yaml](https://github.com/lym29/UniDexGrasp/blob/main/dexgrasp_generation/configs/model/ipdf.yaml), it is
```yaml
network:
  type: pn_rotation_net

number_fourier_components: 1
mlp_layer_sizes: [256, 256, 256]
num_train_queries: 4096

loss_weight:
  log_prob: 1.0
```

So I replace 'pn_rotation_net' with 'epn_net'. But there is a new error when running the eval code, which indicates that the value of  equi_feat_mlps is not given. 
>omegaconf.errors.ConfigKeyError: Key 'equi_feat_mlps' is not in struct
>full_key: model.network.equi_feat_mlps
>object_type=dict

I am wondering if you could provide a new config file for ipdf.

BTW, I would greatly appreciate it if you could clarify which networks these different types refer to. Thanks!

**Comment by lym29** [comment]
I have made several attempts to modify the code. One of the changes I made was replacing 'pn_rotation_net' with 'epn_net' in the rotation net configuration. Additionally, I added an 'equi_feat_mlps' parameter in the ipdf.yaml file, which now appears as follows:

```yaml
network:
  type: epn_net
  equi_feat_mlps: [64, 64, 64]
  # type: pn_rotation_net

number_fourier_components: 1
mlp_layer_sizes: [256, 256, 256]
num_train_queries: 4096

loss_weight:
  log_prob: 1.0

```
To address the issue of incompatible dimensions in the geometric features extracted by the backbone, I made a specific modification to the pointnet++ encoder. I adjusted the output dimension of the third linear layer from 128 to 64. 

These are all the modification I have done. I am afraid that these are not your original network architecture. 

Please let me know if these modifications align with the desired changes or if there are any further adjustments needed.

Thank you!
